### ISSUE TITLE
node's interface mac-address setting

### ISSUE THREAD

**Issue by slankdev** [slankdev/tinet#16]
```
nodes:
  - name: CLOS
    image: slankdev/centos-frr-dev:7
    interfaces:
      - { name: net0, type: direct, args: R1#net0, addr: "52:54:00:11:11:11" }
      - { name: net1, type: direct, args: R2#net0, addr: "52:54:00:22:22:22" }
```
